const fs = require('fs');
const path = require('path');

const filePaths = {
  page: path.join(__dirname, 'src/app/admin/page.tsx'),
  charts: path.join(__dirname, 'src/app/admin/charts.tsx'),
  questionEditor: path.join(__dirname, 'src/app/admin/question-editor.tsx'),
  adminGuide: path.join(__dirname, 'src/app/admin/admin-guide.tsx')
};

// --- Translate charts.tsx ---
let chartsContent = fs.readFileSync(filePaths.charts, 'utf8');
chartsContent = chartsContent
    .replace(/"Số bài"/g, '"Count"')
    .replace(/"TB \(%\)"/g, '"Avg (%)"')
    .replace(/"Bài nộp"/g, '"Submissions"');
fs.writeFileSync(filePaths.charts, chartsContent);

// --- Translate admin-guide.tsx ---
let guideContent = fs.readFileSync(filePaths.adminGuide, 'utf8');
guideContent = guideContent
    .replace(/Hướng dẫn sử dụng Admin Dashboard/g, 'Admin Dashboard User Guide')
    .replace(/Đăng nhập Admin/g, 'Admin Login')
    .replace(/Truy cập trang(.*?)và nhập mã PIN được cấp. Bấm icon/g, 'Access the$1page and enter the provided PIN. Click the')
    .replace(/để hiện mật khẩu kiểm tra trước khi đăng nhập./g, 'icon to view the password before logging in.')
    .replace(/Tab Tổng quan/g, 'Overview Tab')
    .replace(/Thống kê nhanh:/g, 'Quick Stats:')
    .replace(/Tổng bài nộp, điểm trung bình, tỷ lệ đạt, số giám khảo/g, 'Total submissions, average score, pass rate, number of judges')
    .replace(/Biểu đồ:/g, 'Charts:')
    .replace(/Phân bổ theo nhóm thi, tỷ lệ đạt\/chưa đạt, phân bổ điểm, điểm TB theo nhóm/g, 'Distribution by test group, pass/fail rate, score distribution, average score by group')
    .replace(/Tải Excel:/g, 'Download Excel:')
    .replace(/Bấm nút "Tải Excel" để xuất toàn bộ dữ liệu bài thi/g, 'Click the "Download Excel" button to export all test data')
    .replace(/Tab Bài nộp/g, 'Submissions Tab')
    .replace(/Xem danh sách tất cả bài nộp của ứng viên/g, 'View the list of all candidate submissions')
    .replace(/Lọc theo nhóm thi \(Finance, SC Planning, SC Logistics\)/g, 'Filter by test group (Finance, SC Planning, SC Logistics)')
    .replace(/Tìm kiếm theo tên hoặc SBD ứng viên/g, 'Search by candidate name or ID')
    .replace(/Bấm vào từng bài để xem chi tiết câu trả lời/g, 'Click on each submission to view detailed answers')
    .replace(/Tab Giám khảo/g, 'Judges Tab')
    .replace(/Thêm giám khảo:/g, 'Add Judge:')
    .replace(/Nhập tên và email, bấm "Thêm"/g, 'Enter name and email, click "Add"')
    .replace(/Xóa giám khảo:/g, 'Delete Judge:')
    .replace(/Bấm nút "✕" bên cạnh giám khảo/g, 'Click the "✕" button next to the judge')
    .replace(/Giám khảo đăng nhập qua email tại trang/g, 'Judges log in via email on the')
    .replace(/Giám khảo sẽ tự nhập điểm cho từng câu hỏi của ứng viên/g, 'Judges will manually enter scores for each question of the candidate')
    .replace(/Tab Bộ đề/g, 'Question Sets Tab')
    .replace(/Xem bộ đề:/g, 'View Question Set:')
    .replace(/Bấm vào tiêu đề bộ đề để mở\/đóng danh sách câu hỏi/g, 'Click on the question set title to expand/collapse the question list')
    .replace(/Thêm bộ đề mới:/g, 'Add New Question Set:')
    .replace(/Bấm "\+ Thêm bộ đề", nhập ID, tiêu đề, icon, thời gian/g, 'Click "+ Add Question Set", enter ID, title, icon, time')
    .replace(/Sửa bộ đề:/g, 'Edit Question Set:')
    .replace(/Bấm icon bút chì, sửa thông tin, bấm "Lưu"/g, 'Click the pencil icon, edit info, click "Save"')
    .replace(/Xóa bộ đề:/g, 'Delete Question Set:')
    .replace(/Bấm icon thùng rác \(sẽ xóa luôn tất cả câu hỏi bên trong\)/g, 'Click the trash icon (will also delete all questions inside)')
    .replace(/Thêm câu hỏi:/g, 'Add Question:')
    .replace(/Mở bộ đề → Bấm "\+ Thêm câu hỏi" ở cuối/g, 'Open question set → Click "+ Add Question" at the bottom')
    .replace(/4 loại câu hỏi:/g, '4 Question Types:')
    .replace(/Trắc nghiệm \(1 đáp án\), Trắc nghiệm \(nhiều đáp án\), Đúng\/Sai, Tự luận/g, 'Single Choice, Multiple Choice, True/False, Essay')
    .replace(/Trang ứng viên/g, 'Candidate Page')
    .replace(/URL dạng:/g, 'URL format:')
    .replace(/Ứng viên nhập thông tin → chọn bộ đề → làm bài → nộp/g, 'Candidate enters info → chooses test group → takes test → submits')
    .replace(/Bài nộp sẽ tự động hiển thị trên Admin Dashboard/g, 'Submissions will automatically appear on the Admin Dashboard')
    .replace(/Liên kết nhanh/g, 'Quick Links')
    .replace(/Trang Admin/g, 'Admin Page')
    .replace(/Trang Giám khảo/g, 'Judge Page')
    .replace(/Trang Thi \(mẫu\)/g, 'Test Page (Sample)')
    .replace(/Cấu trúc dữ liệu/g, 'Data Structure')
    .replace(/>Bảng</g, '>Table<')
    .replace(/>Mô tả</g, '>Description<')
    .replace(/Bộ đề thi \(tiêu đề, thời gian, icon\)/g, 'Question sets (title, duration, icon)')
    .replace(/Câu hỏi \(nội dung, loại, đáp án, điểm\)/g, 'Questions (content, type, answer, points)')
    .replace(/Bài nộp của ứng viên/g, 'Candidate submissions')
    .replace(/Danh sách giám khảo/g, 'List of judges')
    .replace(/Điểm chấm từ giám khảo/g, 'Scores from judges')
    .replace(/Link thi tùy chỉnh/g, 'Custom test links');
fs.writeFileSync(filePaths.adminGuide, guideContent);


// --- Translate question-editor.tsx ---
let qeContent = fs.readFileSync(filePaths.questionEditor, 'utf8');
qeContent = qeContent
    .replace(/Trắc nghiệm \(1 đáp án\)/g, 'Single Choice')
    .replace(/Trắc nghiệm \(nhiều đáp án\)/g, 'Multiple Choice')
    .replace(/Đúng \/ Sai/g, 'True / False')
    .replace(/"Tự luận"/g, '"Essay"')
    .replace(/"Xóa bộ đề"/g, '"Delete test group"')
    .replace(/Xóa bộ đề "(.*?)" và toàn bộ câu hỏi bên trong\?/g, 'Delete test group "$1" and all questions inside?')
    .replace(/Xóa câu hỏi này\?/g, 'Delete this question?')
    .replace(/Đang tải bộ đề\.\.\./g, 'Loading question sets...')
    .replace(/Quản lý bộ đề thi/g, 'Manage Question Sets')
    .replace(/\({groups\.length} bộ\)/g, '({groups.length} sets)')
    .replace(/> Thêm bộ đề</g, '> Add Question Set<')
    .replace(/Tạo bộ đề mới/g, 'Create New Question Set')
    .replace(/>Tiêu đề</g, '>Title<')
    .replace(/Thời gian \(phút\)/g, 'Duration (minutes)')
    .replace(/>Mô tả</g, '>Description<')
    .replace(/Mô tả ngắn về bộ đề/g, 'Short description of the test group')
    .replace(/"Đang lưu\.\.\."/g, '"Saving..."')
    .replace(/"Tạo bộ đề"/g, '"Create Set"')
    .replace(/>Hủy</g, '>Cancel<')
    .replace(/>phút</g, '>min<')
    .replace(/>Lưu</g, '>Save<')
    .replace(/ câu · /g, ' questions · ')
    .replace(/ điểm · /g, ' pts · ')
    .replace(/ phút</g, ' min<')
    .replace(/>Ẩn</g, '>Hidden<')
    .replace(/"Sửa"/g, '"Edit"')
    .replace(/"Xóa"/g, '"Delete"')
    .replace(/> Thêm câu hỏi/g, '> Add Question')
    .replace(/Loại câu hỏi/g, 'Question Type')
    .replace(/Nội dung câu hỏi/g, 'Question Content')
    .replace(/Nhập nội dung câu hỏi\.\.\./g, 'Enter question content...')
    .replace(/>Điểm</g, '>Points<')
    .replace(/Hình ảnh minh họa \(tùy chọn\)/g, 'Illustrative Image (optional)')
    .replace(/"Xóa ảnh"/g, '"Delete Image"')
    .replace(/Đáp án/g, 'Answers')
    .replace(/chọn nhiều/g, 'multiple choice')
    .replace(/chọn 1/g, 'single choice')
    .replace(/Đáp án đúng/g, 'Correct Answer')
    .replace(/> Đúng</g, '> True<')
    .replace(/"Đúng"/g, '"True"')
    .replace(/> Sai</g, '> False<')
    .replace(/"Sai"/g, '"False"')
    .replace(/Đáp án gợi ý \(dùng để chấm tham khảo\)/g, 'Suggested Answer (for reference grading)')
    .replace(/Nhập từ khóa \/ đáp án mẫu\.\.\./g, 'Enter keywords / sample answer...')
    .replace(/> Thêm đáp án</g, '> Add option<')
    .replace(/\{q.points\}đ/g, '{q.points}pts');
fs.writeFileSync(filePaths.questionEditor, qeContent);

// --- Translate page.tsx ---
let pageContent = fs.readFileSync(filePaths.page, 'utf8');
pageContent = pageContent
    .replace(/Mã PIN không đúng/g, 'Incorrect PIN')
    .replace(/Xóa giám khảo này\?/g, 'Delete this judge?')
    .replace(/"Số báo danh"/g, '"ID"')
    .replace(/"Họ tên"/g, '"Name"')
    .replace(/"Email"/g, '"Email"')
    .replace(/"SĐT"/g, '"Phone"')
    .replace(/"Nhóm thi"/g, '"Group"')
    .replace(/"Điểm"/g, '"Score"')
    .replace(/"Tổng điểm"/g, '"Total Score"')
    .replace(/"Phần trăm \(%\)"/g, '"Percentage (%)"')
    .replace(/"Kết quả"/g, '"Result"')
    .replace(/"Đạt"/g, '"Passed"')
    .replace(/"Chưa đạt"/g, '"Failed"')
    .replace(/"Thời gian nộp"/g, '"Submission Time"')
    .replace(/ans\.correct \? "Đúng" : "Sai"/g, 'ans.correct ? "Correct" : "Incorrect"')
    .replace(/`Điểm C\$\{idx \+ 1\}`/g, '`Score Q${idx + 1}`')
    .replace(/"Kết quả thi"/g, '"Test Results"')
    .replace(/"Vai trò"/g, '"Role"')
    .replace(/"Giám khảo"/g, '"Judge"')
    .replace(/Nhập mã PIN để truy cập hệ thống quản lý/g, 'Enter PIN to access management system')
    .replace(/>Đăng nhập</g, '>Login<')
    .replace(/"Hiện mật khẩu"/g, '"Show password"')
    .replace(/"Ẩn mật khẩu"/g, '"Hide password"')
    .replace(/Tải Excel/g, 'Download Excel')
    .replace(/>Đăng xuất</g, '>Logout<')
    .replace(/Tổng quan/g, 'Overview')
    .replace(/Bài nộp/g, 'Submissions')
    .replace(/> Giám khảo</g, '> Judges<')
    .replace(/Bộ đề/g, 'Question Sets')
    .replace(/Hướng dẫn/g, 'Guide')
    .replace(/Đang tải dữ liệu\.\.\./g, 'Loading data...')
    .replace(/Tổng bài nộp/g, 'Total submissions')
    .replace(/ứng viên đã thi/g, 'candidates tested')
    .replace(/Điểm trung bình/g, 'Average Score')
    .replace(/trung bình % đạt/g, 'avg pass %')
    .replace(/Tỷ lệ đạt/g, 'Pass Rate')
    .replace(/≥ 70% đạt chuẩn/g, '≥ 70% passing standard')
    .replace(/>Giám khảo</g, '>Judges<')
    .replace(/người đang hoạt động/g, 'active members')
    .replace(/Phân bổ theo nhóm thi/g, 'Distribution by group')
    .replace(/Tỷ lệ Đạt \/ Chưa đạt/g, 'Pass / Fail Ratio')
    .replace(/Phân bổ điểm số/g, 'Score Distribution')
    .replace(/Điểm trung bình theo nhóm/g, 'Average Score by Group')
    .replace(/Số bài nộp theo ngày/g, 'Submissions by Date')
    .replace(/Bài nộp gần đây/g, 'Recent Submissions')
    .replace(/>SBD</g, '>ID<')
    .replace(/>Họ tên</g, '>Name<')
    .replace(/>Nhóm</g, '>Group<')
    .replace(/>Điểm</g, '>Score<')
    .replace(/>Thời gian</g, '>Time<')
    .replace(/Tất cả bài nộp/g, 'All Submissions')
    .replace(/Tìm tên, email, SBD\.\.\./g, 'Search name, email, ID...')
    .replace(/Tất cả nhóm/g, 'All Groups')
    .replace(/>Kết quả</g, '>Result<')
    .replace(/Không có bài nộp nào/g, 'No submissions found')
    .replace(/Thêm giám khảo mới/g, 'Add New Judge')
    .replace(/Nhập họ tên/g, 'Enter name')
    .replace(/>Vai trò</g, '>Role<')
    .replace(/>Thêm</g, '>Add<')
    .replace(/"Xóa"/g, '"Delete"')
    .replace(/Chi tiết bài nộp/g, 'Submission Details')
    .replace(/>Nhóm thi</g, '>Group<')
    .replace(/Điểm tự động/g, 'Auto Score')
    .replace(/Câu trả lời \(/g, 'Answers (')
    .replace(/câu\)/g, 'questions)')
    .replace(/>Câu /g, '>Question ')
    .replace(/Câu hỏi #/g, 'Question #')
    .replace(/Trả lời:/g, 'Answer:')
    .replace(/ điểm</g, ' pts<')
    .replace(/Chấm điểm giám khảo/g, 'Judge Grading')
    .replace(/Nhận xét/g, 'Notes')
    .replace(/Ghi chú nhận xét cho ứng viên\.\.\./g, 'Notes for the candidate...')
    .replace(/Đang lưu\.\.\./g, 'Saving...')
    .replace(/Lưu điểm/g, 'Save Score')
    .replace(/Điểm đã chấm/g, 'Graded Scores')
    .replace(/"GK"/g, '"Judge"')
    .replace(/Tùy chỉnh xuất Excel/g, 'Excel Export Options')
    .replace(/Lọc theo nhóm thi/g, 'Filter by test group')
    .replace(/Thông tin ứng viên/g, 'Candidate Info')
    .replace(/Chọn tất cả/g, 'Select All')
    .replace(/Bỏ chọn/g, 'Deselect')
    .replace(/"Số điện thoại"/g, '"Phone"')
    .replace(/Chi tiết câu trả lời từng câu/g, 'Detailed answers for each question')
    .replace(/Sheet danh sách Giám khảo/g, 'Judges List Sheet')
    .replace(/>Hủy</g, '>Cancel<')
    .replace(/Tải xuống/g, 'Download')
    .replace(/Nội dung bổ sung/g, 'Additional Content')
    .replace(/Câu /g, 'Q');

fs.writeFileSync(filePaths.page, pageContent);

console.log('Translated successfully!');
